// Generated by dts-bundle-generator v9.5.1

import { BaseChatModel } from '@langchain/core/language_models/chat_models';

declare enum TacticName {
	Heuristic = "heuristic",
	LanguageModel = "language_model",
	Pattern = "pattern"
}
export interface TacticExecution {
	score: number;
	additionalFields?: Record<string, unknown>;
}
export interface Tactic {
	readonly name: TacticName;
	readonly defaultThreshold: number;
	execute(input: string, thresholdOverride?: number): Promise<TacticExecution>;
}
declare class Heuristic implements Tactic {
	private readonly keywords;
	readonly name = TacticName.Heuristic;
	readonly defaultThreshold: number;
	constructor(threshold: number, keywords: string[]);
	execute(input: string, thresholdOverride?: number): Promise<TacticExecution>;
}
declare class Pattern implements Tactic {
	private readonly patterns;
	readonly name = TacticName.Pattern;
	readonly defaultThreshold: number;
	constructor(threshold: number | undefined, patterns: RegExp[]);
	execute(input: string, thresholdOverride?: number): Promise<TacticExecution>;
}
declare class LanguageModel implements Tactic {
	private readonly llm;
	private renderPromptTemplate;
	readonly name = TacticName.LanguageModel;
	readonly defaultThreshold: number;
	constructor(threshold: number | undefined, llm: BaseChatModel, renderPromptTemplate: (input: string) => string);
	execute(input: string, thresholdOverride?: number): Promise<TacticExecution>;
}
export declare const InjectionKeywords: string[];
export declare const InjectionPatterns: RegExp[];
export declare function RenderPromptForInjectionDetection(userInput: string): string;
export declare const heuristicInjectionTactic: Heuristic;
export declare const patternInjectionTactic: Pattern;
export declare const languageModelInjectionTactic: (llm: BaseChatModel) => LanguageModel;
export declare const LeakingKeywords: string[];
export declare const LeakingPatterns: RegExp[];
export declare function RenderPromptForLeakingDetection(userInput: string): string;
export declare const heuristicLeakingTactic: Heuristic;
export declare const patternLeakingTactic: Pattern;
export declare const languageModelLeakingTactic: (llm: BaseChatModel) => LanguageModel;

export {};
